export const API_TOKEN = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2ODkzMzgwNzUsImlzcyI6ImVLYXJ0IiwiZXhwIjoxNjg5MzM5ODc1LCJzdWIiOiJlS2FydCBBdXRoZW50aWNhdGlvbiJ9.npZY8mIpAc6yeesEFdZmyV4ju5yyuapVoX3iDValJ8k';

 